apiVersion: v1
kind: PersistentVolumeClaim
metadata:
  name: pvc-todo-list
  namespace: todo-list
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 1Gi
  storageClassName: azurefile
